yarnPath: .yarn/releases/yarn-4.0.2.cjs
packageExtensions:
  "local-pkg@*":
    dependencies:
      "happy-dom": "^14.7.1"
  "swiper@*":
    dependencies:
      "react": "^18.0.2"
  "@aws-sdk/core@*":
    dependencies:
      "tslib": "*"
  "react-intersection-observer@*":
    dependencies:
      "react-dom": "*"
